### ISSUE TITLE
"user" table in Postgres isn't copied

### ISSUE THREAD

**Issue by laggingreflex** [simonw/db-to-sqlite#25]
If you have a table named "user" in PostgreSQL it isn't copied. 

It does create the table, but the entries do not reflect the original table. The entries I see are just one row "1 postgres". 

It seems the issue is that in Postgres `user` [is a pseudo-function keyword][1] 

[1]: https://dba.stackexchange.com/questions/75551/returning-rows-in-postgresql-with-a-table-called-user/75559#75559

**Comment by simonw** [comment]
Presumably this is caused by: https://github.com/simonw/db-to-sqlite/blob/bd199449367e32650b399041eec837982f016da7/db_to_sqlite/cli.py#L88-L92

That `select * from {table}` query needs to somehow grow awareness of database engine specific escaping conventions for table names.

**Comment by simonw** [comment]
Looks like I need to figure out how to call `quote_identifier` in SQLAlchemy for the current engine's database dialect: https://docs.sqlalchemy.org/en/14/core/internals.html#sqlalchemy.sql.compiler.IdentifierPreparer.quote_identifier

**Comment by simonw** [comment]
Searched here: https://github.com/search?l=Python&q=engine+quote_identifier&type=Code

https://github.com/bluelabsio/records-mover/blob/e3b71d6c09d99d0bcd6a956b9d09d20f8abe98d2/records_mover/db/quoting.py#L60

```python
def quote_group_name(db: Union[Connection, Engine], group_name: str) -> str:
    dialect = db.dialect
    return dialect.preparer(dialect).quote_identifier(group_name)
```
